# Kibana Configuration - Minimal to avoid permission issues
server.port: 5601
server.host: "0.0.0.0"
server.name: "kibana-server"

# Elasticsearch connection
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Security (for development)
xpack.security.enabled: false

# UI Settings
map.includeElasticMapsService: false
telemetry.enabled: false
newsfeed.enabled: false
